#%RAML 1.0
---
title: Locations
version: v1
baseUri: "{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
#===============================================================
# API resource definitions
#===============================================================
/locations:
  displayName: Locations
  get:
    responses:
      200:
        body:
          application/json:
            example:
              !include mock-data.json